<?php

namespace App\Repositories;

class CategoryRepositories
{
    public static function getAll(): array
    {
        return [
            [
                'id' => 1,
                'slug' => 'semen-pasir-mortar',
                'name' => 'Semen, Pasir & Mortar',
                'description' => 'Semen Portland, semen instan, mortar perekat bata ringan, acian, serta pasir pasang dan pasir cor berkualitas tinggi.',
                'status' => 'active',
                'count' => 8,
                'count_label' => '8 Produk',
                'image' => 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 1,
            ],
            [
                'id' => 2,
                'slug' => 'cat-finishing',
                'name' => 'Cat & Finishing',
                'description' => 'Pilihan cat tembok interior dan eksterior, cat besi & kayu, kuas, roller, pelapis anti bocor, dan perlengkapan finishing.',
                'status' => 'active',
                'count' => 7,
                'count_label' => '7 Produk',
                'image' => 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 2,
            ],
            [
                'id' => 3,
                'slug' => 'besi-baja',
                'name' => 'Besi & Baja',
                'description' => 'Besi beton polos dan ulir, baja ringan, wiremesh, kawat ikatan, dan struktur logam standar SNI untuk konstruksi kokoh.',
                'status' => 'active',
                'count' => 7,
                'count_label' => '7 Produk',
                'image' => 'https://images.unsplash.com/photo-1535813547-99c456a41d4a?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Kota Baru'],
                'popular_rank' => 3,
            ],
            [
                'id' => 4,
                'slug' => 'pipa-plumbing',
                'name' => 'Pipa & Plumbing',
                'description' => 'Sistem saluran air lengkap dengan pipa PVC & HDPE, fitting, kran air, aksesoris plumbing, dan perlengkapan sanitari.',
                'status' => 'active',
                'count' => 7,
                'count_label' => '7 Produk',
                'image' => 'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Gajahmada', 'Kota Baru'],
                'popular_rank' => 4,
            ],
            [
                'id' => 5,
                'slug' => 'atap-aksesoris',
                'name' => 'Atap & Aksesoris',
                'description' => 'Atap spandek, polycarbonate, seng gelombang, talang air, nok atap, dan aksesoris perlindungan bocor tahan lama.',
                'status' => 'active',
                'count' => 6,
                'count_label' => '6 Produk',
                'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 5,
            ],
            [
                'id' => 6,
                'slug' => 'kayu-papan',
                'name' => 'Kayu & Papan',
                'description' => 'Kayu balok meranti, kaso, papan triplek, plywood, GRC board, dan kayu konstruksi pilihan dengan ketahanan terbaik.',
                'status' => 'active',
                'count' => 6,
                'count_label' => '6 Produk',
                'image' => 'https://images.unsplash.com/photo-1546484475-7f7bd55792da?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada'],
                'popular_rank' => 6,
            ],
            [
                'id' => 7,
                'slug' => 'peralatan-perkakas',
                'name' => 'Peralatan & Perkakas',
                'description' => 'Perkakas tangan, power tools, bor listrik, gerinda, palu, meteran, dan alat kerja pertukangan profesional.',
                'status' => 'active',
                'count' => 6,
                'count_label' => '6 Produk',
                'image' => 'https://images.unsplash.com/photo-1581244277943-fe4a9c777189?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 7,
            ],
            [
                'id' => 8,
                'slug' => 'lantai',
                'name' => 'Lantai',
                'description' => 'Penutup lantai modern seperti granit tile, vinyl floor, lantai kayu SPC, dan parket dengan beragam motif indah.',
                'status' => 'active',
                'count' => 5,
                'count_label' => '5 Produk',
                'image' => 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Kota Baru'],
                'popular_rank' => 8,
            ],
            [
                'id' => 9,
                'slug' => 'keramik',
                'name' => 'Keramik',
                'description' => 'Keramik lantai & dinding bermotif elegan, keramik kamar mandi, keramik dapur, dan lis keramik berkualitas.',
                'status' => 'active',
                'count' => 6,
                'count_label' => '6 Produk',
                'image' => 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 9,
            ],
            [
                'id' => 10,
                'slug' => 'elektrikal',
                'name' => 'Elektrikal',
                'description' => 'Kabel listrik Eterna, sakelar, stopkontak, lampu LED, MCB, pipa conduit, dan kebutuhan instalasi listrik aman.',
                'status' => 'active',
                'count' => 6,
                'count_label' => '6 Produk',
                'image' => 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Gajahmada', 'Kota Baru'],
                'popular_rank' => 10,
            ],
            [
                'id' => 11,
                'slug' => 'pondasi-beton',
                'name' => 'Pondasi & Beton',
                'description' => 'Batu split, batu kali, beton instan, buis beton, cakar ayam, dan material struktur pondasi rumah kokoh.',
                'status' => 'active',
                'count' => 6,
                'count_label' => '6 Produk',
                'image' => 'https://images.unsplash.com/photo-1541888946425-d0fbb186a5b7?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Kota Baru'],
                'popular_rank' => 11,
            ],
            [
                'id' => 12,
                'slug' => 'kaca-aluminium',
                'name' => 'Kaca & Aluminium',
                'description' => 'Kusen aluminium, kaca tempered, kaca cermin, engsel, dan perlengkapan pintu & jendela modern.',
                'status' => 'active',
                'count' => 5,
                'count_label' => '5 Produk',
                'image' => 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Gajahmada', 'Kota Baru'],
                'popular_rank' => 12,
            ],
            [
                'id' => 13,
                'slug' => 'perekat-sealant',
                'name' => 'Perekat & Sealant',
                'description' => 'Lem keramik & granit, silicone sealant waterproof, perekat kayu/besi, dan pengisi nat tahan air.',
                'status' => 'active',
                'count' => 5,
                'count_label' => '5 Produk',
                'image' => 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 13,
            ],
            [
                'id' => 14,
                'slug' => 'tangki-air-pompa',
                'name' => 'Tangki Air & Pompa',
                'description' => 'Toren/tangki air bersih, pompa air pendorong, pompa sumur dalam, radar otomatis, dan aksesoris penampungan air.',
                'status' => 'active',
                'count' => 5,
                'count_label' => '5 Produk',
                'image' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada'],
                'popular_rank' => 14,
            ],
            [
                'id' => 15,
                'slug' => 'genteng',
                'name' => 'Genteng',
                'description' => 'Genteng keramik, genteng metal, genteng beton, genteng tanah liat, dan nok genteng berkualitas tinggi.',
                'status' => 'active',
                'count' => 5,
                'count_label' => '5 Produk',
                'image' => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Gajahmada', 'Kota Baru'],
                'popular_rank' => 15,
            ],
            [
                'id' => 16,
                'slug' => 'insulation',
                'name' => 'Insulation',
                'description' => 'Peredam panas aluminium foil, bubble foil, glasswool, rockwool, dan peredam suara untuk kenyamanan bangunan.',
                'status' => 'active',
                'count' => 3,
                'count_label' => '3 Produk',
                'image' => 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Kota Baru'],
                'popular_rank' => 16,
            ],
            [
                'id' => 17,
                'slug' => 'alat-keselamatan',
                'name' => 'Alat Keselamatan',
                'description' => 'Perlengkapan APD K3: helm proyek, sepatu safety, sarung tangan kerja, kacamata pelindung, dan rompi keselamatan.',
                'status' => 'active',
                'count' => 3,
                'count_label' => '3 Produk',
                'image' => 'https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 17,
            ],
            [
                'id' => 18,
                'slug' => 'batu-tanah',
                'name' => 'Batu dan Tanah',
                'description' => 'Batu kali, batu belah, batu koral, tanah urug, tanah taman, dan batu hias untuk pondasi maupun pekerjaan lansekap.',
                'status' => 'active',
                'count' => 4,
                'count_label' => '4 Produk',
                'image' => 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=600&auto=format&fit=crop&q=80',
                'branches' => ['Serdam', 'Gajahmada', 'Kota Baru'],
                'popular_rank' => 18,
            ],
        ];
    }
}
